import { defineConfig } from 'tsup';

export default defineConfig({
	entry: [
		'src/index.ts',
		'src/core/index.ts',
		'src/fn/index.ts',
		'src/methods/index.ts',
		// Individual method modules for tree-shaking
		'src/methods/avg.ts',
		'src/methods/chunk.ts',
		'src/methods/contains.ts',
		'src/methods/each.ts',
		'src/methods/every.ts',
		'src/methods/filter.ts',
		'src/methods/first.ts',
		'src/methods/flatMap.ts',
		'src/methods/groupBy.ts',
		'src/methods/keyBy.ts',
		'src/methods/last.ts',
		'src/methods/map.ts',
		'src/methods/max.ts',
		'src/methods/min.ts',
		'src/methods/partition.ts',
		'src/methods/pluck.ts',
		'src/methods/reduce.ts',
		'src/methods/reject.ts',
		'src/methods/skip.ts',
		'src/methods/some.ts',
		'src/methods/sortBy.ts',
		'src/methods/sum.ts',
		'src/methods/take.ts',
		'src/methods/tap.ts',
		'src/methods/unique.ts',
	],
	format: ['esm'],
	dts: false, // Using tsc directly for declarations (TS7 compatibility)
	clean: true,
	sourcemap: true,
	minify: true,
	target: 'es2022',
	outDir: 'dist',
});
