import { defineConfig } from 'tsup';

export default defineConfig({
	entry: [
		'src/index.ts',
		'src/core/index.ts',
		'src/fn/index.ts',
		'src/methods/index.ts',
		'src/plugin/index.ts',
		'src/plugin/transform.ts',
		'src/plugin/webpack-loader.ts',
		// Individual method modules for tree-shaking
		'src/methods/avg.ts',
		'src/methods/chunk.ts',
		'src/methods/collapse.ts',
		'src/methods/concat.ts',
		'src/methods/contains.ts',
		'src/methods/count.ts',
		'src/methods/each.ts',
		'src/methods/every.ts',
		'src/methods/except.ts',
		'src/methods/filter.ts',
		'src/methods/first.ts',
		'src/methods/flatMap.ts',
		'src/methods/flatten.ts',
		'src/methods/flip.ts',
		'src/methods/groupBy.ts',
		'src/methods/join.ts',
		'src/methods/keyBy.ts',
		'src/methods/keys.ts',
		'src/methods/last.ts',
		'src/methods/map.ts',
		'src/methods/max.ts',
		'src/methods/merge.ts',
		'src/methods/min.ts',
		'src/methods/only.ts',
		'src/methods/partition.ts',
		'src/methods/pluck.ts',
		'src/methods/reduce.ts',
		'src/methods/reject.ts',
		'src/methods/reverse.ts',
		'src/methods/shuffle.ts',
		'src/methods/skip.ts',
		'src/methods/slice.ts',
		'src/methods/some.ts',
		'src/methods/sortBy.ts',
		'src/methods/sum.ts',
		'src/methods/take.ts',
		'src/methods/tap.ts',
		'src/methods/unique.ts',
		'src/methods/values.ts',
		'src/methods/where.ts',
		'src/methods/whereIn.ts',
	],
	format: ['esm'],
	dts: false, // Using tsc directly for declarations (TS7 compatibility)
	clean: true,
	sourcemap: true,
	minify: true,
	target: 'es2022',
	outDir: 'dist',
});
