name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Minimal code to reproduce the issue
      placeholder: |
        ```typescript
        import { collect } from 'collect-ts';

        const result = collect([1, 2, 3]).someMethod();
        // Expected: ...
        // Actual: ...
        ```
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: collect-ts version
      placeholder: "0.2.0"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      placeholder: "20.10.0"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
